"""添加tips列到表中

Revision ID: cc73066facd9
Revises: 
Create Date: 2024-07-31 22:41:56.485967

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'cc73066facd9'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('crypto', schema=None) as batch_op:
        batch_op.add_column(sa.Column('tips', sa.String(length=255), nullable=True))

    with op.batch_alter_table('misc', schema=None) as batch_op:
        batch_op.add_column(sa.Column('tips', sa.String(length=255), nullable=True))

    with op.batch_alter_table('pwn', schema=None) as batch_op:
        batch_op.add_column(sa.Column('tips', sa.String(length=255), nullable=True))

    with op.batch_alter_table('reverse', schema=None) as batch_op:
        batch_op.add_column(sa.Column('tips', sa.String(length=255), nullable=True))

    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.alter_column('password_hash',
               existing_type=mysql.VARCHAR(length=256),
               type_=sa.String(length=255),
               existing_nullable=True)

    with op.batch_alter_table('web', schema=None) as batch_op:
        batch_op.add_column(sa.Column('tips', sa.String(length=255), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('web', schema=None) as batch_op:
        batch_op.drop_column('tips')

    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.alter_column('password_hash',
               existing_type=sa.String(length=255),
               type_=mysql.VARCHAR(length=256),
               existing_nullable=True)

    with op.batch_alter_table('reverse', schema=None) as batch_op:
        batch_op.drop_column('tips')

    with op.batch_alter_table('pwn', schema=None) as batch_op:
        batch_op.drop_column('tips')

    with op.batch_alter_table('misc', schema=None) as batch_op:
        batch_op.drop_column('tips')

    with op.batch_alter_table('crypto', schema=None) as batch_op:
        batch_op.drop_column('tips')

    # ### end Alembic commands ###
